apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: graf
spec:
  selector:
    app: graf
  type: NodePort
  ports:
   - nodePort: 31340
     port: 3000
     targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc
  labels:
    name: graf
spec:
  accessModes:
   - ReadWriteOnce
  resources:  
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: graf
  labels:
    app: graf
spec:
  selector:
    matchLabels:
      app: graf
  strategy:
    type: Recreate
  template:
    metadata:
      name: mycon1
      labels:
        app: graf
    spec:
      containers:
      - image: vimal13/grafana
        name: graf
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: graf-pvc
          mountPath: /var/lib/grafana	
        securityContext:
          allowPrivilegeEscalation: false  
      volumes:
      - name: graf-pvc
        persistentVolumeClaim:
          claimName: graf-pvc
        
    